#spring.application.name=patient-microservice
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#
## H2 Console
#spring.h2.console.enabled=true
##spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.path=/h2-console
#
## JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
##spring.sql.init.mode=always
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.datasource.url=jdbc:postgresql://localhost:6433/patientdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true